In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv(r"B:\SIH2\AI-Pollution-Forecast-and-Policy-Dashboard\ML\Raw\TROPOMI\tropomi_no2_hourly_2023_2025_real.csv")

In [4]:
df

,datetime,mean_concentration,data_source
0,2023-01-01 00:00:00,1.196896e+20,tropomi_observed_or_interpolated
1,2023-01-01 01:00:00,1.196896e+20,tropomi_observed_or_interpolated
2,2023-01-01 02:00:00,1.196896e+20,tropomi_observed_or_interpolated
3,2023-01-01 03:00:00,1.196896e+20,tropomi_observed_or_interpolated
4,2023-01-01 04:00:00,1.196896e+20,tropomi_observed_or_interpolated
...,...,...,...
26299,2025-12-31 19:00:00,8.564856e+19,extrapolated_from_last_2023_value
26300,2025-12-31 20:00:00,8.564856e+19,extrapolated_from_last_2023_value
26301,2025-12-31 21:00:00,8.564856e+19,extrapolated_from_last_2023_value
26302,2025-12-31 22:00:00,8.564856e+19,extrapolated_from_last_2023_value
26303,2025-12-31 23:00:00,8.564856e+19,extrapolated_from_last_2023_value

In [5]:
print(df.shape)
print(df.dtypes)
df.isnull().sum()

(26304, 3)
datetime               object
mean_concentration    float64
data_source            object
dtype: object

datetime              0
mean_concentration    0
data_source           0
dtype: int64

In [6]:
no2 = df['mean_concentration']

In [7]:
df['no2_normalized'] = (no2 - no2.min()) / (no2.max() - no2.min())

In [8]:
df['no2_normalized']

0        1.000000
1        1.000000
2        1.000000
3        1.000000
4        1.000000
           ...
26299    0.473666
26300    0.473666
26301    0.473666
26302    0.473666
26303    0.473666
Name: no2_normalized, Length: 26304, dtype: float64

In [9]:
df['hour'] = pd.to_datetime(df['datetime']).dt.hour

In [10]:
df['traffic_peak'] = df['hour'].apply(
    lambda h: 1 if (7 <= h <= 10) or (17 <= h <= 20) else 0
)

In [11]:
df

,datetime,mean_concentration,data_source,no2_normalized,hour,traffic_peak
0,2023-01-01 00:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.000000,0,0
1,2023-01-01 01:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.000000,1,0
2,2023-01-01 02:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.000000,2,0
3,2023-01-01 03:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.000000,3,0
4,2023-01-01 04:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.000000,4,0
...,...,...,...,...,...,...
26299,2025-12-31 19:00:00,8.564856e+19,extrapolated_from_last_2023_value,0.473666,19,1
26300,2025-12-31 20:00:00,8.564856e+19,extrapolated_from_last_2023_value,0.473666,20,1
26301,2025-12-31 21:00:00,8.564856e+19,extrapolated_from_last_2023_value,0.473666,21,0
26302,2025-12-31 22:00:00,8.564856e+19,extrapolated_from_last_2023_value,0.473666,22,0
26303,2025-12-31 23:00:00,8.564856e+19,extrapolated_from_last_2023_value,0.473666,23,0

In [12]:
df['traffic_no2'] = df['no2_normalized'] * df['traffic_peak']
df['industrial_no2'] = df['no2_normalized'] * (1 - df['traffic_peak'])

In [13]:
df['data_source'].value_counts()

data_source
extrapolated_from_last_2023_value    17904
tropomi_observed_or_interpolated      8400
Name: count, dtype: int64

In [14]:
df.to_csv("Tropomi_2023_2025.csv",index=False)

In [15]:
df = pd.read_csv("Tropomi_2023_2025.csv")
df.head()

,datetime,mean_concentration,data_source,no2_normalized,hour,traffic_peak,traffic_no2,industrial_no2
0,2023-01-01 00:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.0,0,0,0.0,1.0
1,2023-01-01 01:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.0,1,0,0.0,1.0
2,2023-01-01 02:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.0,2,0,0.0,1.0
3,2023-01-01 03:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.0,3,0,0.0,1.0
4,2023-01-01 04:00:00,1.196896e+20,tropomi_observed_or_interpolated,1.0,4,0,0.0,1.0