In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_excel(r"C:\Users\samru\OneDrive\Desktop\SIH_2025\AI-Pollution-Forecast-and-Policy-Dashboard\ML\Raw\CCR_DATA_2023_25\2025_Alipur, Delhi - DPCC.xlsx")

In [4]:
df

,CENTRAL POLLUTION CONTROL BOARD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,CONTINUOUS AMBIENT AIR QUALITY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Date: Sunday, Nov 16 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Time: 10:41:48 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,State,Delhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,City,Delhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,12-11-2025 00:00,13-11-2025 00:00,358.79,586.61,7.78,64.01,40.38,16.31,16.14,1.91,...,8.52,0.09,NaN,55.52,76.05,992.79,NaN,19.3,0,0
332,13-11-2025 00:00,14-11-2025 00:00,281.78,529.52,11.93,69.95,46.9,16.3,11.57,1.8,...,6.65,0.07,NaN,57.3,142.51,994.18,NaN,19.05,0,0
333,14-11-2025 00:00,15-11-2025 00:00,236.54,432.08,6.66,73.96,47.71,14.81,12.59,1.51,...,6.16,0.21,0.01,56.82,63.98,994.21,NaN,18.99,0,0
334,15-11-2025 00:00,16-11-2025 00:00,276.46,476.79,9.18,69.22,44.28,36.35,11.97,1.57,...,7.85,0.22,0.01,57.69,102.16,995.22,NaN,18.74,0,0
335,16-11-2025 00:00,16-11-2025 22:41,292.43,482.88,11.12,57.85,39.81,55.07,14.64,1.58,...,4.76,0.04,NaN,56.15,186.43,997.09,NaN,18.86,0,0

In [5]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   CENTRAL POLLUTION CONTROL BOARD  335 non-null    object
 1   Unnamed: 1                       330 non-null    object
 2   Unnamed: 2                       322 non-null    object
 3   Unnamed: 3                       322 non-null    object
 4   Unnamed: 4                       322 non-null    object
 5   Unnamed: 5                       322 non-null    object
 6   Unnamed: 6                       321 non-null    object
 7   Unnamed: 7                       322 non-null    object
 8   Unnamed: 8                       317 non-null    object
 9   Unnamed: 9                       322 non-null    object
 10  Unnamed: 10                      320 non-null    object
 11  Unnamed: 11                      321 non-null    object
 12  Unnamed: 12                      321 non-null    object
 13  Unnamed: 13                      226 non-null    object
 14  Unnamed: 14                      159 non-null    object
 15  Unnamed: 15                      321 non-null    object
 16  Unnamed: 16                      321 non-null    object
 17  Unnamed: 17                      321 non-null    object
 18  Unnamed: 18                      1 non-null      object
 19  Unnamed: 19                      321 non-null    object
 20  Unnamed: 20                      321 non-null    object
 21  Unnamed: 21                      321 non-null    object
dtypes: object(22)
memory usage: 57.9+ KB

(336, 22)

In [6]:
# Show basic info
display(df.head())
display(df.info())  # see data types and missing values

,CENTRAL POLLUTION CONTROL BOARD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,CONTINUOUS AMBIENT AIR QUALITY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Date: Sunday, Nov 16 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Time: 10:41:48 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,State,Delhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,City,Delhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   CENTRAL POLLUTION CONTROL BOARD  335 non-null    object
 1   Unnamed: 1                       330 non-null    object
 2   Unnamed: 2                       322 non-null    object
 3   Unnamed: 3                       322 non-null    object
 4   Unnamed: 4                       322 non-null    object
 5   Unnamed: 5                       322 non-null    object
 6   Unnamed: 6                       321 non-null    object
 7   Unnamed: 7                       322 non-null    object
 8   Unnamed: 8                       317 non-null    object
 9   Unnamed: 9                       322 non-null    object
 10  Unnamed: 10                      320 non-null    object
 11  Unnamed: 11                      321 non-null    object
 12  Unnamed: 12                      321 non-null    object
 13  Unnamed: 13                      226 non-null    object
 14  Unnamed: 14                      159 non-null    object
 15  Unnamed: 15                      321 non-null    object
 16  Unnamed: 16                      321 non-null    object
 17  Unnamed: 17                      321 non-null    object
 18  Unnamed: 18                      1 non-null      object
 19  Unnamed: 19                      321 non-null    object
 20  Unnamed: 20                      321 non-null    object
 21  Unnamed: 21                      321 non-null    object
dtypes: object(22)
memory usage: 57.9+ KB

None

In [7]:
print("Shape before removing duplicates:", df.shape)
df = df.drop_duplicates().reset_index(drop=True)
print("Shape after removing duplicates:", df.shape)

Shape before removing duplicates: (336, 22)
Shape after removing duplicates: (336, 22)

In [8]:
num_cols = df.select_dtypes(include=[np.number]).columns
cat_cols = df.select_dtypes(exclude=[np.number]).columns

# Fill numeric columns with mean
for col in num_cols:
    mean_val = df[col].mean()
    df[col] = df[col].fillna(mean_val)

# Fill categorical columns with mode (most frequent value)
for col in cat_cols:
    if df[col].isnull().any():
        mode_val = df[col].mode(dropna=True)
        if not mode_val.empty:
            df[col] = df[col].fillna(mode_val[0])

# Check missing values again
print(df.isna().sum())

CENTRAL POLLUTION CONTROL BOARD    0
Unnamed: 1                         0
Unnamed: 2                         0
Unnamed: 3                         0
Unnamed: 4                         0
Unnamed: 5                         0
Unnamed: 6                         0
Unnamed: 7                         0
Unnamed: 8                         0
Unnamed: 9                         0
Unnamed: 10                        0
Unnamed: 11                        0
Unnamed: 12                        0
Unnamed: 13                        0
Unnamed: 14                        0
Unnamed: 15                        0
Unnamed: 16                        0
Unnamed: 17                        0
Unnamed: 18                        0
Unnamed: 19                        0
Unnamed: 20                        0
Unnamed: 21                        0
dtype: int64

In [9]:
def cap_outliers_iqr(data, cols):
    df_capped = data.copy()
    for col in cols:
        Q1 = df_capped[col].quantile(0.25)
        Q3 = df_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        df_capped[col] = np.where(df_capped[col] < lower, lower, df_capped[col])
        df_capped[col] = np.where(df_capped[col] > upper, upper, df_capped[col])
    return df_capped

df = cap_outliers_iqr(df, num_cols)

In [10]:
df

,CENTRAL POLLUTION CONTROL BOARD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,CONTINUOUS AMBIENT AIR QUALITY,,16.75,55.42,3.1,16.83,12.81,16.28,3.65,0.45,...,0.25,0.02,0.01,52.32,138.32,980.67,Xylene,29.98,0,0
1,"Date: Sunday, Nov 16 2025",,16.75,55.42,3.1,16.83,12.81,16.28,3.65,0.45,...,0.25,0.02,0.01,52.32,138.32,980.67,Xylene,29.98,0,0
2,Time: 10:41:48 PM,,16.75,55.42,3.1,16.83,12.81,16.28,3.65,0.45,...,0.25,0.02,0.01,52.32,138.32,980.67,Xylene,29.98,0,0
3,State,Delhi,16.75,55.42,3.1,16.83,12.81,16.28,3.65,0.45,...,0.25,0.02,0.01,52.32,138.32,980.67,Xylene,29.98,0,0
4,City,Delhi,16.75,55.42,3.1,16.83,12.81,16.28,3.65,0.45,...,0.25,0.02,0.01,52.32,138.32,980.67,Xylene,29.98,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,12-11-2025 00:00,13-11-2025 00:00,358.79,586.61,7.78,64.01,40.38,16.31,16.14,1.91,...,8.52,0.09,0.01,55.52,76.05,992.79,Xylene,19.3,0,0
332,13-11-2025 00:00,14-11-2025 00:00,281.78,529.52,11.93,69.95,46.9,16.3,11.57,1.8,...,6.65,0.07,0.01,57.3,142.51,994.18,Xylene,19.05,0,0
333,14-11-2025 00:00,15-11-2025 00:00,236.54,432.08,6.66,73.96,47.71,14.81,12.59,1.51,...,6.16,0.21,0.01,56.82,63.98,994.21,Xylene,18.99,0,0
334,15-11-2025 00:00,16-11-2025 00:00,276.46,476.79,9.18,69.22,44.28,36.35,11.97,1.57,...,7.85,0.22,0.01,57.69,102.16,995.22,Xylene,18.74,0,0
335,16-11-2025 00:00,16-11-2025 22:41,292.43,482.88,11.12,57.85,39.81,55.07,14.64,1.58,...,4.76,0.04,0.01,56.15,186.43,997.09,Xylene,18.86,0,0