In [47]:
import pandas as pd
import numpy as np

In [49]:
df=pd.read_excel(r"C:\Users\samru\OneDrive\Desktop\SIH_2025\AI-Pollution-Forecast-and-Policy-Dashboard\ML\Raw\CCR_DATA_2023_25\2025_Anand Vihar, Delhi - DPCC.xlsx",skiprows=16)

In [50]:
df

,From Date,To Date,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,Ozone,Benzene,Toluene,RH,WS,WD,BP,AT,RF,TOT-RF
0,01-01-2025 00:00,02-01-2025 00:00,207.96,327.35,76.34,70.21,99.41,74.43,12.16,2.13,4.17,4.15,43.95,78.91,0.70,217.51,739.98,12.25,NaN,0
1,02-01-2025 00:00,03-01-2025 00:00,208.17,319.46,66.57,67.96,85.17,83.13,7.86,2.16,4.55,4.13,40.82,80.20,0.75,179.94,739.97,12.30,NaN,0
2,03-01-2025 00:00,04-01-2025 00:00,470.81,675.09,163.89,117.78,176.84,117.57,23.07,3.04,5.39,7.07,63.73,80.02,0.54,244.63,739.83,14.15,NaN,0
3,04-01-2025 00:00,05-01-2025 00:00,358.85,454.33,94.80,82.99,130.12,118.83,12.07,2.78,7.14,9.09,69.52,87.75,1.46,250.26,739.49,12.97,NaN,0
4,05-01-2025 00:00,06-01-2025 00:00,190.02,269.27,36.41,54.28,58.45,58.02,9.62,1.73,5.16,4.95,41.19,80.54,1.91,235.91,739.22,12.97,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,12-11-2025 00:00,13-11-2025 00:00,347.31,541.81,93.74,139.10,135.44,59.58,51.45,3.56,13.99,6.80,44.32,53.95,0.61,144.50,735.06,18.53,NaN,0
316,13-11-2025 00:00,14-11-2025 00:00,328.68,553.73,102.05,136.57,148.20,56.26,48.58,3.02,12.89,7.21,53.58,57.47,0.47,182.37,735.34,18.03,NaN,0
317,14-11-2025 00:00,15-11-2025 00:00,273.34,482.37,85.25,110.01,122.75,49.94,38.16,3.50,6.24,7.85,57.46,58.31,0.45,164.37,735.19,17.56,NaN,0
318,15-11-2025 00:00,16-11-2025 00:00,267.06,471.04,95.61,116.89,130.65,55.59,38.16,3.39,6.55,8.08,57.06,55.94,0.76,207.16,734.51,18.02,NaN,0
319,16-11-2025 00:00,16-11-2025 22:42,275.49,456.29,88.68,111.31,122.27,51.02,45.09,3.06,5.97,7.33,48.25,54.81,0.31,177.07,735.21,18.10,NaN,0

In [51]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   From Date  320 non-null    object
 1   To Date    320 non-null    object
 2   PM2.5      318 non-null    float64
 3   PM10       319 non-null    float64
 4   NO         320 non-null    float64
 5   NO2        320 non-null    float64
 6   NOx        320 non-null    float64
 7   NH3        320 non-null    float64
 8   SO2        315 non-null    float64
 9   CO         320 non-null    float64
 10  Ozone      319 non-null    float64
 11  Benzene    316 non-null    float64
 12  Toluene    316 non-null    float64
 13  RH         320 non-null    float64
 14  WS         320 non-null    float64
 15  WD         319 non-null    float64
 16  BP         320 non-null    float64
 17  AT         320 non-null    float64
 18  RF         0 non-null      float64
 19  TOT-RF     320 non-null    int64
dtypes: float64(17), int64(1), object(2)
memory usage: 50.1+ KB

(320, 20)

In [52]:
# Show basic info
display(df.head())
display(df.info())  # see data types and missing values

,From Date,To Date,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,Ozone,Benzene,Toluene,RH,WS,WD,BP,AT,RF,TOT-RF
0,01-01-2025 00:00,02-01-2025 00:00,207.96,327.35,76.34,70.21,99.41,74.43,12.16,2.13,4.17,4.15,43.95,78.91,0.70,217.51,739.98,12.25,NaN,0
1,02-01-2025 00:00,03-01-2025 00:00,208.17,319.46,66.57,67.96,85.17,83.13,7.86,2.16,4.55,4.13,40.82,80.20,0.75,179.94,739.97,12.30,NaN,0
2,03-01-2025 00:00,04-01-2025 00:00,470.81,675.09,163.89,117.78,176.84,117.57,23.07,3.04,5.39,7.07,63.73,80.02,0.54,244.63,739.83,14.15,NaN,0
3,04-01-2025 00:00,05-01-2025 00:00,358.85,454.33,94.80,82.99,130.12,118.83,12.07,2.78,7.14,9.09,69.52,87.75,1.46,250.26,739.49,12.97,NaN,0
4,05-01-2025 00:00,06-01-2025 00:00,190.02,269.27,36.41,54.28,58.45,58.02,9.62,1.73,5.16,4.95,41.19,80.54,1.91,235.91,739.22,12.97,NaN,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   From Date  320 non-null    object
 1   To Date    320 non-null    object
 2   PM2.5      318 non-null    float64
 3   PM10       319 non-null    float64
 4   NO         320 non-null    float64
 5   NO2        320 non-null    float64
 6   NOx        320 non-null    float64
 7   NH3        320 non-null    float64
 8   SO2        315 non-null    float64
 9   CO         320 non-null    float64
 10  Ozone      319 non-null    float64
 11  Benzene    316 non-null    float64
 12  Toluene    316 non-null    float64
 13  RH         320 non-null    float64
 14  WS         320 non-null    float64
 15  WD         319 non-null    float64
 16  BP         320 non-null    float64
 17  AT         320 non-null    float64
 18  RF         0 non-null      float64
 19  TOT-RF     320 non-null    int64
dtypes: float64(17), int64(1), object(2)
memory usage: 50.1+ KB

None

In [53]:
# Convert date columns to datetime
df['From Date'] = pd.to_datetime(df['From Date'], errors='coerce')
df['To Date'] = pd.to_datetime(df['To Date'], errors='coerce')

# If you want to remove rows where dates could not be parsed (became NaT)
df = df.dropna(subset=['From Date', 'To Date'])

In [54]:
print("Shape before removing duplicates:", df.shape)
df = df.drop_duplicates().reset_index(drop=True)
print("Shape after removing duplicates:", df.shape)

Shape before removing duplicates: (121, 20)
Shape after removing duplicates: (121, 20)

In [55]:
num_cols = df.select_dtypes(include=[np.number]).columns
cat_cols = df.select_dtypes(exclude=[np.number]).columns

# Fill numeric columns with mean
for col in num_cols:
    mean_val = df[col].mean()
    df[col] = df[col].fillna(mean_val)

# Fill categorical columns with mode (most frequent value)
for col in cat_cols:
    if df[col].isnull().any():
        mode_val = df[col].mode(dropna=True)
        if not mode_val.empty:
            df[col] = df[col].fillna(mode_val[0])

# Check missing values again
print(df.isna().sum())

From Date      0
To Date        0
PM2.5          0
PM10           0
NO             0
NO2            0
NOx            0
NH3            0
SO2            0
CO             0
Ozone          0
Benzene        0
Toluene        0
RH             0
WS             0
WD             0
BP             0
AT             0
RF           121
TOT-RF         0
dtype: int64

In [56]:
def cap_outliers_iqr(data, cols):
    df_capped = data.copy()
    for col in cols:
        Q1 = df_capped[col].quantile(0.25)
        Q3 = df_capped[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        df_capped[col] = np.where(df_capped[col] < lower, lower, df_capped[col])
        df_capped[col] = np.where(df_capped[col] > upper, upper, df_capped[col])
    return df_capped

df = cap_outliers_iqr(df, num_cols)

In [57]:
df

,From Date,To Date,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,Ozone,Benzene,Toluene,RH,WS,WD,BP,AT,RF,TOT-RF
0,2025-01-01,2025-02-01,207.960,327.35,76.34,70.210,99.41,74.430,12.16,2.13,4.170,4.15,43.95,78.91,0.700,217.51,739.98,12.25,NaN,0.0
1,2025-02-01,2025-03-01,208.170,319.46,66.57,67.960,85.17,83.130,7.86,2.16,4.550,4.13,40.82,80.20,0.750,179.94,739.97,12.30,NaN,0.0
2,2025-03-01,2025-04-01,228.785,570.47,163.89,117.780,176.84,86.035,23.07,3.04,5.390,7.07,63.73,80.02,0.540,244.63,739.83,14.15,NaN,0.0
3,2025-04-01,2025-05-01,228.785,454.33,94.80,82.990,130.12,86.035,12.07,2.78,7.140,8.57,66.88,87.75,1.405,250.26,739.49,12.97,NaN,0.0
4,2025-05-01,2025-06-01,190.020,269.27,36.41,54.280,58.45,58.020,9.62,1.73,5.160,4.95,41.19,80.54,1.405,235.91,739.22,12.97,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,2025-07-11,2025-08-11,228.785,408.08,36.65,102.970,82.62,40.960,36.23,3.25,35.495,4.60,29.76,47.52,0.440,130.49,735.15,22.25,NaN,0.0
117,2025-08-11,2025-09-11,228.785,472.78,61.47,127.900,111.01,41.280,39.67,3.67,35.495,5.88,35.71,47.67,1.400,161.21,735.25,21.84,NaN,0.0
118,2025-09-11,2025-10-11,228.785,410.38,63.06,138.580,119.81,45.720,43.76,3.56,35.495,5.78,36.88,49.02,1.405,134.49,735.30,22.08,NaN,0.0
119,2025-10-11,2025-11-11,228.785,487.23,91.06,142.865,145.50,52.450,47.63,4.18,33.510,7.33,52.98,53.31,0.870,130.29,735.29,21.41,NaN,0.0
120,2025-11-11,2025-12-11,228.785,560.38,103.14,142.865,162.86,62.290,48.42,3.48,18.070,7.80,64.92,54.54,0.700,93.65,735.39,18.67,NaN,0.0

In [60]:
df.to_excel('Anand_vihar2025.xlsx', index=False)